

def find_missing_residues(sys: Structure) -> "list[GapDescriptor]": ...
def find_missing_atoms(sys: Structure, template: str = "ccd") -> "list[MissingAtomDescriptor]": ...
def find_nonstandard_residues(sys: Structure) -> "list[NonstandardResidueDescriptor]": ...
def replace_nonstandard_residues(sys: Structure) -> Structure: ...
def remove_heterogens(sys: Structure, keep_water: bool = True) -> Structure: ...
def remove_chains(
    sys: Structure,
    chain_ids: Optional["list[str]"] = None,
    chain_indices: Optional["list[int]"] = None,
) -> Structure: ...
def apply_mutations(sys: Structure, mutations: "list[tuple[str, int, str]]") -> Structure: ...
def add_missing_atoms(sys: Structure, template: str = "ccd") -> Structure: ...
def set_protonation(sys: Structure, target, state: str) -> Structure: ...
def complete_loops(sys: Structure, method: str = "trim", **kwargs) -> Structure:
    """method ∈ {"trim" (native), "pdbfixer", "openfold"}."""
    ...
def add_hydrogens(sys: Structure, pH: float = 7.0, forcefield=None) -> Structure: ...  # pdbfixer
def add_solvent(sys: Structure, **kwargs) -> Structure: ...   # pdbfixer
def add_membrane(sys: Structure, **kwargs) -> Structure: ...  # pdbfixer